### ISSUE TITLE
Where is origin/upstream repo for exodus?

### ISSUE THREAD

**Issue by timkindberg** [MrLegendary/plugin.video.exodus#1]
Hi I'm looking to fork exodus' main repo but having trouble finding it? Where did you fork from?

I want to add a 'Recent' section, cause I hate always navigating back to things I'm in the middle of.

**Comment by lrfvk** [comment]
Just take the plugin.video.exodus folder from the kodi folder on your computer and upload it to GitHub. 

Not sure where the original repo is. I use the tvaddons exodus repo.
